wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1656002681
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 35
      4: 3.8.13
      5: 0.12.18
      8:
      - 5
